// constants/dogNames.ts

export const DOGS = [
    { name: 'Buddy', age: 5, behavior: 'Playful', color: 'Brown' },
    { name: 'Max', age: 3, behavior: 'Energetic', color: 'Black' },
    { name: 'Charlie', age: 7, behavior: 'Loyal', color: 'Golden' },
    { name: 'Lucy', age: 2, behavior: 'Curious', color: 'White' },
    { name: 'Cooper', age: 4, behavior: 'Friendly', color: 'Black and White' },
    { name: 'Rocky', age: 6, behavior: 'Adventurous', color: 'Gray' },
    { name: 'Daisy', age: 1, behavior: 'Timid', color: 'Brown' },
    { name: 'Bella', age: 8, behavior: 'Confident', color: 'Cream' },
    { name: 'Gracie', age: 9, behavior: 'Gentle', color: 'Black' },
    { name: 'Bear', age: 5, behavior: 'Protective', color: 'Brown' },
    { name: 'Molly', age: 3, behavior: 'Affectionate', color: 'White' },
    { name: 'Cody', age: 6, behavior: 'Mischievous', color: 'Black' },
    { name: 'Duke', age: 7, behavior: 'Loyal', color: 'Golden' },
    { name: 'Luna', age: 2, behavior: 'Dreamy', color: 'Gray' },
    { name: 'Finn', age: 4, behavior: 'Energetic', color: 'Brown' },
    { name: 'Sadie', age: 8, behavior: 'Sassy', color: 'White' },
    { name: 'Maggie', age: 9, behavior: 'Maternal', color: 'Black' },
    { name: 'Abby', age: 5, behavior: 'Playful', color: 'Golden' },
    { name: 'Rufus', age: 6, behavior: 'Goofy', color: 'Brown' },
    { name: 'Toby', age: 3, behavior: 'Curious', color: 'White' },
    { name: 'Bailey', age: 7, behavior: 'Friendly', color: 'Cream' },
    { name: 'Ginger', age: 2, behavior: 'Feisty', color: 'Red' },
    { name: 'Sammy', age: 4, behavior: 'Lively', color: 'Brown' },
    { name: 'Lola', age: 8, behavior: 'Sassy', color: 'Black' },
    { name: 'Coco', age: 9, behavior: 'Sweet', color: 'Brown' },
    { name: 'Chloe', age: 5, behavior: 'Playful', color: 'White' },
    { name: 'Zoe', age: 6, behavior: 'Energetic', color: 'Black' },
    { name: 'Hunter', age: 7, behavior: 'Adventurous', color: 'Golden' },
    { name: 'Sasha', age: 3, behavior: 'Curious', color: 'Gray' },
    { name: 'Rusty', age: 4, behavior: 'Loyal', color: 'Red' },
    { name: 'Lucky', age: 2, behavior: 'Timid', color: 'Brown' },
    { name: 'Dixie', age: 8, behavior: 'Sassy', color: 'Black and White' },
    { name: 'Baxter', age: 9, behavior: 'Gentle', color: 'Brown' },
    { name: 'Gizmo', age: 5, behavior: 'Mischievous', color: 'White' },
    { name: 'Sparky', age: 6, behavior: 'Energetic', color: 'Gray' },
    { name: 'Oliver', age: 7, behavior: 'Confident', color: 'Black' },
    { name: 'Cora', age: 3, behavior: 'Curious', color: 'Golden' },
    { name: 'Nala', age: 4, behavior: 'Loyal', color: 'Brown' },
    { name: 'Jasper', age: 2, behavior: 'Timid', color: 'White' },
    { name: 'Willow', age: 8, behavior: 'Dreamy', color: 'Gray' },
    { name: 'Riley', age: 9, behavior: 'Friendly', color: 'Cream' },
    { name: 'Sandy', age: 5, behavior: 'Playful', color: 'Golden' },
    { name: 'Casey', age: 6, behavior: 'Energetic', color: 'Black' },
    { name: 'Tucker', age: 7, behavior: 'Adventurous', color: 'Brown' },
    { name: 'Lily', age: 3, behavior: 'Curious', color: 'White' },
    { name: 'Peanut', age: 4, behavior: 'Loyal', color: 'Tan' },
    { name: 'Maverick', age: 2, behavior: 'Mischievous', color: 'Black and White' },
    { name: 'Dakota', age: 8, behavior: 'Confident', color: 'Gray' },
    { name: 'Chester', age: 9, behavior: 'Gentle', color: 'Brown' },
    { name: 'Brandy', age: 5, behavior: 'Sassy', color: 'Black' },
    { name: 'Scooter', age: 6, behavior: 'Energetic', color: 'White' },
];

// { name: 'Cinnamon', age: 7, behavior: 'Sweet' },
// { name: 'Nugget', age: 3, behavior: 'Curious' },
// { name: 'Bristol', age: 4, behavior: 'Loyal' },
// { name: 'Rowdy', age: 2, behavior: 'Mischievous' },
// { name: 'Savannah', age: 8, behavior: 'Dreamy' },
// { name: 'Journey', age: 9, behavior: 'Friendly' },
// { name: 'Ranger', age: 5, behavior: 'Adventurous' },
// { name: 'Lacey', age: 6, behavior: 'Playful' },
// { name: 'Cami', age: 7, behavior: 'Confident' },
// { name: 'Bentley', age: 3, behavior: 'Curious' },
// { name: 'Paisley', age: 4, behavior: 'Loyal' },
// { name: 'Gatsby', age: 2, behavior: 'Mischievous' },
// { name: 'Remi', age: 8, behavior: 'Sassy' },
// { name: 'Indie', age: 9, behavior: 'Gentle' },
// { name: 'Oakley', age: 5, behavior: 'Energetic' },
// { name: 'Sage', age: 6, behavior: 'Dreamy' },
// { name: 'River', age: 7, behavior: 'Adventurous' },
// { name: 'August', age: 3, behavior: 'Curious' },
// { name: 'Piper', age: 4, behavior: 'Loyal' },
// { name: 'Salem', age: 2, behavior: 'Timid' },
// { name: 'Winston', age: 8, behavior: 'Confident' },
// { name: 'Lylah', age: 9, behavior: 'Friendly' },
// { name: 'Caspian', age: 5, behavior: 'Playful' },
// { name: 'Orion', age: 6, behavior: 'Energetic' },
// { name: 'Vega', age: 7, behavior: 'Dreamy' },
// { name: 'Lunaire', age: 3, behavior: 'Curious' },
// { name: 'Aurora', age: 4, behavior: 'Loyal' },
// { name: 'Cosmo', age: 2, behavior: 'Mischievous' },
// { name: 'Nova', age: 8, behavior: 'Sassy' },
// { name: 'Stella', age: 9, behavior: 'Gentle' },
// { name: 'Romeo', age: 5, behavior: 'Romantic' },
// { name: 'Juliet', age: 6, behavior: 'Dramatic' },
// { name: 'Bruno', age: 7, behavior: 'Loyal' },
// { name: 'Cleo', age: 3, behavior: 'Curious' },
// { name: 'Dino', age: 4, behavior: 'Playful' },
// { name: 'Fifi', age: 2, behavior: 'Timid' },
// { name: 'Gigi', age: 8, behavior: 'Sassy' },
// { name: 'Hank', age: 9, behavior: 'Friendly' },
// { name: 'Ivy', age: 5, behavior: 'Dreamy' },
// { name: 'Jinx', age: 6, behavior: 'Mischievous' },
// { name: 'Kai', age: 7, behavior: 'Adventurous' },
// { name: 'Lola', age: 3, behavior: 'Curious' },
// { name: 'Miko', age: 4, behavior: 'Loyal' },
// { name: 'Niko', age: 2, behavior: 'Timid' },
// { name: 'Odie', age: 8, behavior: 'Sassy' },
// { name: 'Paco', age: 9, behavior: 'Gentle' },
// { name: 'Quincy', age: 5, behavior: 'Energetic' },
// { name: 'Rico', age: 6, behavior: 'Playful' },
// { name: 'Santo', age: 7, behavior: 'Loyal' },
// { name: 'Tango', age: 3, behavior: 'Curious' },
// { name: 'Uma', age: 4, behavior: 'Playful' },
// { name: 'Vinnie', age: 2, behavior: 'Mischievous' },
// { name: 'Wally', age: 8, behavior: 'Friendly' },
// { name: 'Xena', age: 9, behavior: 'Confident' },
// { name: 'Yuri', age: 5, behavior: 'Energetic' },
// { name: 'Zelda', age: 6, behavior: 'Dreamy' },
// { name: 'Ava', age: 7, behavior: 'Loyal' },
// { name: 'Bodie', age: 3, behavior: 'Curious' },
// { name: 'Cali', age: 4, behavior: 'Playful' },
// { name: 'Dakota', age: 2, behavior: 'Timid' },
// { name: 'Echo', age: 8, behavior: 'Sassy' },
// { name: 'Finnley', age: 9, behavior: 'Gentle' },
// { name: 'Gwen', age: 5, behavior: 'Energetic' },
// { name: 'Haven', age: 6, behavior: 'Dreamy' },
// { name: 'Izzy', age: 7, behavior: 'Loyal' },
// { name: 'Jagger', age: 3, behavior: 'Curious' },
// { name: 'Kaius', age: 4, behavior: 'Playful' },
// { name: 'Luna', age: 2, behavior: 'Mischievous' },
// { name: 'Maeve', age: 8, behavior: 'Sassy' },
// { name: 'Nash', age: 9, behavior: 'Friendly' },
// { name: 'Ophelia', age: 5, behavior: 'Energetic' },
// { name: 'Piper', age: 6, behavior: 'Dreamy' },
// { name: 'Quinn', age: 7, behavior: 'Loyal' },
// { name: 'Remy', age: 3, behavior: 'Curious' },
// { name: 'Sage', age: 4, behavior: 'Playful' },
// { name: 'Tatum', age: 2, behavior: 'Timid' },
// { name: 'Una', age: 8, behavior: 'Sassy' },
// { name: 'Veda', age: 9, behavior: 'Gentle' },
// { name: 'Wiley', age: 5, behavior: 'Energetic' },
// { name: 'Xanthe', age: 6, behavior: 'Dreamy' },
// { name: 'Yara', age: 7, behavior: 'Loyal' },
// { name: 'Zara', age: 3, behavior: 'Curious' },
